#!/usr/bin/env bash

set -euo pipefail

# Default services, have to be declared before sourcing framework.sh so the user can override them
declare -A services
services["SSH"]="sshd"

source "$BASE_DIR/framework.sh"

statuses=()
for key in "${!services[@]}"; do
    # systemctl is-active returns non-zero code if service is inactive
    set +e; status=$(systemctl is-active ${services[$key]}); set -e
    statuses+=("$(print_status "$key" "$status")")
done

text="$(print_wrap $WIDTH "${statuses[@]}")"

print_columns "Services" "$text"
